<?php

/**
 * @file
 * Primary module hooks for Ajax alter title module.
 */

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Ajax\HtmlCommand;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ajax_alter_title_form_node_page_edit_form_alter(&$form, $form_state, $form_id) {
	$form['canceled_title'] = [
		'#type' => 'button',
		'#value' => t('Add "CANCELED" prefix'),
		'#arg' => 'CANCELED',
		'#ajax' => [
			'callback' => 'ajax_alter_title_prefix',
			'wrapper' => 'edit-title-0-value',
			'event' => 'click',
			'progress' => [
				'type' => 'throbber',
				'message' => 'Updating title...'
			]
		]
	];

	$form['postponed_title'] = [
		'#type' => 'button',
		'#value' => t('Add "POSTPONED" prefix'),
		'#arg' => 'POSTPONED',
		'#ajax' => [
			'callback' => 'ajax_alter_title_prefix',
			'wrapper' => 'edit-title-0-value',
			'event' => 'click',
			'progress' => [
				'type' => 'throbber',
				'message' => 'Updating title...'
			]
		]
	];

	$form['sold_out_title'] = [
		'#type' => 'button',
		'#value' => t('Add "SOLD OUT" prefix'),
		'#arg' => 'SOLD OUT',
		'#ajax' => [
			'callback' => 'ajax_alter_title_prefix',
			'wrapper' => 'edit-title-0-value',
			'event' => 'click',
			'progress' => [
				'type' => 'throbber',
				'message' => 'Updating title...'
			]
		]
	];

	$form['delete_title'] = [
		'#type' => 'button',
		'#value' => t('Delete current prefix'),
		'#arg' => 'delete',
		'#ajax' => [
			'callback' => 'ajax_alter_title_prefix',
			'wrapper' => 'edit-title-0-value',
			'event' => 'click',
			'progress' => [
				'type' => 'throbber',
				'message' => 'Deleting preffix...'
			]
		]
	];

	$form['message_title'] = [
		'#type' => 'markup',
		'#markup' => '<div id="message-title"></div>',
	];

}

/**
 * AJAX callback to add or delete prefixes.
 *
 * @param array &$form
 *   The form structure.
 * @param FormStateInterface &$form_state
 *   The current state of the form.
 *
 * @return \Drupal\Core\Ajax\AjaxResponse
 *   An AJAX response that updates the title field and displays a status message.
 */
function ajax_alter_title_prefix(&$form, &$form_state) {
  $response = new AjaxResponse();
	$current_title = $form['title']['widget'][0]['value']['#default_value'];
	$prefix = $form_state->getTriggeringElement()['#arg'];
	$default_options = ['CANCELED', 'POSTPONED', 'SOLD OUT'];

	if (in_array($prefix, $default_options)) {
		$parameters = ajax_alter_title_get_parameters($current_title, $prefix);
	}
	else {
		$parameters = ajax_alter_title_get_parameters_delete($current_title);
	}

	$response->addCommand(new InvokeCommand('#edit-title-0-value', 'val', [$parameters[0]]));
  $response->addCommand(new HtmlCommand('#message-title', $parameters[1]));
	return $response;
}

/**
 * Gets new title and message.
 *
 * @param string $current_title
 *   The current title of the node.
 * @param string $prefix
 *   The prefix to be added to the title.
 *
 * @return array
 *   An array containing:
 *   - The modified title (string).
 *   - A message indicating the status of the operation (string).
 */
function ajax_alter_title_get_parameters($current_title, $prefix) {
	if (!str_starts_with($current_title, $prefix)) {
		$current_title = preg_replace('/^(CANCELED \/|POSTPONED \/|SOLD OUT \/)\s*/', '', $current_title);
    $new_title = $prefix . ' / ' . $current_title;
		$message = '<p style="color:red;">"' . $prefix . '" has been added. Please, <b>save this node</b></p>';
  }
	else {
    $new_title = $current_title;
		$message = '<p style="color:red;">"' . $prefix . '" is already in the original title.</p>';
  }

	$result = [$new_title, $message];
	return $result;
}

/**
 * Gets new title and message when deleting any prefix.
 *
 * @param string $current_title
 *   The current title of the node.
 *
 * @return array
 *   An array containing:
 *   - The modified title (string).
 *   - A message indicating whether a prefix was removed or no change was needed (string).
 */
function ajax_alter_title_get_parameters_delete($current_title) {
	if (preg_match('/^(CANCELED|POSTPONED|SOLD OUT)/', $current_title)) {
		$new_title = preg_replace('/^(CANCELED \/|POSTPONED \/|SOLD OUT \/)\s*/', '', $current_title);
		$message = '<p style="color:red;">Prefix has been deleted. Please, <b>save this node</b></p>';
	}
	else {
		$new_title = $current_title;
		$message = '<p style="color:red;">There is no prefix in the original title. </p>';
	}

	$result = [$new_title, $message];
	return $result;
}